/**
 * Dummy Product Data — all generic/no brands
 */
export const products = [
  {
    id: '1',
    name: 'Generic Granola',
    size: '500g',
    price: 269,
    mrp: 350,
    discount: 23,
    rating: 4.3,
    ratingCount: 128,
    category: 'breakfast',
    emoji: '🥣',
    bgColor: '#FFF3E0',
    description: 'A crunchy and delicious granola mix made with whole grains, nuts, and dried fruits. Perfect for a healthy breakfast.',
  },
  {
    id: '2',
    name: 'Organic Green Tea',
    size: '100g',
    price: 199,
    mrp: 280,
    discount: 29,
    rating: 4.5,
    ratingCount: 256,
    category: 'beverages',
    emoji: '🍵',
    bgColor: '#E8F5E9',
    description: 'Premium organic green tea leaves sourced from sustainable farms. Rich in antioxidants with a smooth taste.',
  },
  {
    id: '3',
    name: 'Artisan Bread',
    size: '400g',
    price: 89,
    mrp: 120,
    discount: 26,
    rating: 4.1,
    ratingCount: 94,
    category: 'bakery',
    emoji: '🍞',
    bgColor: '#FFF8E1',
    description: 'Freshly baked artisan bread made with premium flour and natural ingredients. Soft inside with a crispy crust.',
  },
  {
    id: '4',
    name: 'Natural Apple Juice',
    size: '1L',
    price: 149,
    mrp: 199,
    discount: 25,
    rating: 4.4,
    ratingCount: 189,
    category: 'beverages',
    emoji: '🧃',
    bgColor: '#FBE9E7',
    description: '100% natural apple juice with no added sugar or preservatives. Cold pressed to retain maximum nutrition.',
  },
  {
    id: '5',
    name: 'Vegan Cookies',
    size: '250g',
    price: 179,
    mrp: 230,
    discount: 22,
    rating: 4.2,
    ratingCount: 76,
    category: 'snacks',
    emoji: '🍪',
    bgColor: '#EFEBE9',
    description: 'Delicious vegan cookies made with plant-based ingredients. Crunchy, flavorful, and guilt-free snacking.',
  },
  {
    id: '6',
    name: 'Gourmet Coffee Beans',
    size: '250g',
    price: 449,
    mrp: 599,
    discount: 25,
    rating: 4.7,
    ratingCount: 312,
    category: 'beverages',
    emoji: '☕',
    bgColor: '#EFEBE9',
    description: 'Premium single-origin coffee beans, medium roasted to perfection. Rich aroma with chocolate and caramel notes.',
  },
  {
    id: '7',
    name: 'Premium Hand Wash',
    size: '300ml',
    price: 129,
    mrp: 175,
    discount: 26,
    rating: 4.0,
    ratingCount: 64,
    category: 'personal_care',
    emoji: '🧴',
    bgColor: '#E3F2FD',
    description: 'Gentle hand wash enriched with natural moisturizers. Cleanses while keeping your hands soft and hydrated.',
  },
  {
    id: '8',
    name: 'Eco-friendly Sunscreen',
    size: '50g',
    price: 349,
    mrp: 450,
    discount: 22,
    rating: 4.3,
    ratingCount: 143,
    category: 'personal_care',
    emoji: '☀️',
    bgColor: '#FFFDE7',
    description: 'Reef-safe sunscreen with SPF 50+ protection. Made with natural minerals and eco-friendly ingredients.',
  },
  {
    id: '9',
    name: 'Handmade Soap Bar',
    size: '100g',
    price: 99,
    mrp: 150,
    discount: 34,
    rating: 4.6,
    ratingCount: 201,
    category: 'personal_care',
    emoji: '🧼',
    bgColor: '#F3E5F5',
    description: 'Artisan handmade soap crafted with essential oils and natural butters. Gentle on skin with a luxurious lather.',
  },
  {
    id: '10',
    name: 'Reusable Straws',
    size: 'Set of 4',
    price: 199,
    mrp: 299,
    discount: 33,
    rating: 4.4,
    ratingCount: 87,
    category: 'eco_living',
    emoji: '🥤',
    bgColor: '#E0F7FA',
    description: 'Stainless steel reusable straws set with cleaning brush. Eco-friendly alternative to plastic straws.',
  },
  {
    id: '11',
    name: 'Organic Pasta',
    size: '500g',
    price: 159,
    mrp: 210,
    discount: 24,
    rating: 4.2,
    ratingCount: 155,
    category: 'pantry',
    emoji: '🍝',
    bgColor: '#FFF8E1',
    description: 'Premium organic durum wheat pasta. Made with traditional methods for the perfect al dente texture.',
  },
];
